Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -1,41 +1,46 @@
-name: Atualizar classificação TETR.IO
+name: update-readme
 
 on:
   schedule:
-    - cron: "0 12 * * 0"
-  workflow_dispatch: 
+  - cron: "0 0 * * *"
+
+  workflow_dispatch:
 
 jobs:
-  update-rank:
+  updateTetrio:
     runs-on: ubuntu-latest
+    permissions:
+      contents: write
 
     steps:
-      - name: clone repository
+      - name: Repo checkout
         uses: actions/checkout@v4
-
-      - name: install deps
-        run: sudo apt-get install -y jq curl
-
-      - name: search my country rank in TETR.IO
-        id: get_rank
+    
+      - name: Get region rank position
         run: |
-          USERNAME="ARAPONGA"
-          API_URL="https://ch.tetr.io/api/users/$USERNAME/summaries/league"
-          
-          response=$(curl -s "$API_URL")
-          country_rank=$(echo "$response" | jq -r '.data.standing_local')
-          
-          echo "Classificação nacional: $country_rank"
-          echo "rank=$country_rank" >> $GITHUB_ENV
+          API_URL="https://ch.tetr.io/api/users/araponga/summaries/league"
+          STANDING_LOCAL_VALUE=$(curl -s "$API_URL" | jq -r '.data.standing_local')
 
-      - name: update README.md
-        run: |
-          sed -i -E "s/#([0-9]+)/#${rank}/" README.md
+          if [ -z "$STANDING_LOCAL_VALUE" ] || [ "$STANDING_LOCAL_VALUE" == "null" ]; then
+            echo "Error extracting 'standing_local' from the API or null value. URL: $API_URL"
+            exit 1
+            
+          else
+            echo "Standing Local extracted: $STANDING_LOCAL_VALUE"
+            
+            sed -E -i "s/(TOP#)([0-9]+)/\1$STANDING_LOCAL_VALUE/" README.md
+          fi
 
-      - name: commit & push
+      - name: Commit changes
         run: |
-          git config user.name "github-actions[bot]"
-          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
-          git add README.md
-          git commit -m "Atualiza classificação nacional TETR.IO para #${rank}" || echo "Nenhuma mudança"
-          git push
+          git config --local user.email "viniciuslsilveira.1201@gmail.com"
+          git config --local user.name "GitHub Action"
+
+          if ! git diff --quiet README.md; then
+            git add README.md
+            git commit -m "Update TETR.IO stats"
+            echo "Changes to README.md commited"
+            git push
+          else
+            echo "Nothing to commit, same rank $STANDING_LOCAL_VALUE"
+          fi
